name: Run Daily Arxiv

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"

jobs:
  sync:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxivscraper
          pip install requests

      - name: Run daily arxiv 
        run: |
          python daily_arxiv.py